name: linux-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get install meson pkg-config gcc ragel lcov gtk-doc-tools libfreetype6-dev libglib2.0-dev libcairo2-dev libicu-dev libgraphite2-dev # libgirepository1.0-dev
    - name: run
      run: meson build -Db_coverage=true -Dglib=true -Dcairo=true -Dicu=true -Dgraphite=true -Dfreetype=true
    - name: ci
      run: meson test --print-errorlogs -Cbuild
    - name: cov
      run: ninja -Cbuild coverage
    - uses: codecov/codecov-action@v1
      with:
        file: build/meson-logs/coverage.xml
